# Generated by Django 5.2.8 on 2025-12-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_usermetainfo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermetainfo',
            name='notify_email',
            field=models.BooleanField(default=False, verbose_name='Email notifications'),
        ),
        migrations.AddField(
            model_name='usermetainfo',
            name='notify_on_comment',
            field=models.BooleanField(default=True, verbose_name='Notify on comments'),
        ),
        migrations.AddField(
            model_name='usermetainfo',
            name='notify_on_follow',
            field=models.BooleanField(default=True, verbose_name='Notify on follows'),
        ),
        migrations.AddField(
            model_name='usermetainfo',
            name='notify_on_mention',
            field=models.BooleanField(default=True, verbose_name='Notify on mentions'),
        ),
        migrations.AddField(
            model_name='usermetainfo',
            name='notify_on_vote',
            field=models.BooleanField(default=True, verbose_name='Notify on votes'),
        ),
    ]
