# Generated by Django 5.2.8 on 2025-12-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_id_alter_postvote_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='activity_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='last_activity_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
